import { ToolPreset, ToolPresetId } from "@/shared/types/presets";

export const toolPresets: ToolPreset[] = [
  {
    id: "ballpoint",
    label: "Шариковая ручка",
    description: "Чёткая ежедневная линия для быстрых заметок.",
    category: "pens",
    defaultColor: "#d7e8ff",
    defaultWidth: 2.2,
    defaultOpacity: 0.92,
    strokeStyle: "solid",
    smoothing: 0.45,
  },
  {
    id: "gel",
    label: "Гелевая ручка",
    description: "Плотная мягкая линия с ярким цветом.",
    category: "pens",
    defaultColor: "#f8fbff",
    defaultWidth: 2.8,
    defaultOpacity: 0.96,
    strokeStyle: "solid",
    smoothing: 0.48,
  },
  {
    id: "fountain",
    label: "Перьевая ручка",
    description: "Контрастная линия для выразительного письма.",
    category: "pens",
    defaultColor: "#9ed0ff",
    defaultWidth: 3.2,
    defaultOpacity: 0.9,
    strokeStyle: "solid",
    smoothing: 0.55,
  },
  {
    id: "technical-pen",
    label: "Капиллярная ручка",
    description: "Тонкая техническая линия для схем и контуров.",
    category: "pens",
    defaultColor: "#d4ecff",
    defaultWidth: 1.6,
    defaultOpacity: 0.95,
    strokeStyle: "solid",
    smoothing: 0.38,
  },
  {
    id: "liner",
    label: "Линер",
    description: "Ровный контур для заметок и черновых чертежей.",
    category: "pens",
    defaultColor: "#f5f7ff",
    defaultWidth: 1.8,
    defaultOpacity: 0.92,
    strokeStyle: "solid",
    smoothing: 0.34,
  },
  {
    id: "marker",
    label: "Маркер",
    description: "Широкая насыщенная полоса для схем и блоков.",
    category: "markers",
    defaultColor: "#7fffd4",
    defaultWidth: 8,
    defaultOpacity: 0.68,
    strokeStyle: "marker",
    smoothing: 0.5,
  },
  {
    id: "highlighter",
    label: "Текстовыделитель",
    description: "Прозрачный акцент под важными фрагментами.",
    category: "markers",
    defaultColor: "#d5ff72",
    defaultWidth: 14,
    defaultOpacity: 0.32,
    strokeStyle: "marker",
    smoothing: 0.42,
  },
  {
    id: "pencil",
    label: "Карандаш",
    description: "Мягкий графитовый набросок с живой линией.",
    category: "pencils",
    defaultColor: "#dbd6c9",
    defaultWidth: 2.6,
    defaultOpacity: 0.72,
    strokeStyle: "grain",
    smoothing: 0.26,
  },
  {
    id: "mechanical-pencil",
    label: "Механический карандаш",
    description: "Точный сухой штрих для схем и заметок.",
    category: "pencils",
    defaultColor: "#ede9dd",
    defaultWidth: 1.5,
    defaultOpacity: 0.78,
    strokeStyle: "grain",
    smoothing: 0.28,
  },
  {
    id: "brush",
    label: "Кисть",
    description: "Пластичная линия для живых акцентов и живописи.",
    category: "brushes",
    defaultColor: "#8de7ff",
    defaultWidth: 5.4,
    defaultOpacity: 0.74,
    strokeStyle: "solid",
    smoothing: 0.62,
  },
  {
    id: "calligraphy-brush",
    label: "Каллиграфическая кисть",
    description: "Эффектный инструмент для надписей и акцентных жестов.",
    category: "brushes",
    defaultColor: "#ffd7b8",
    defaultWidth: 6.6,
    defaultOpacity: 0.86,
    strokeStyle: "solid",
    smoothing: 0.64,
  },
  {
    id: "thin-brush",
    label: "Тонкая кисть",
    description: "Контролируемая тонкая кисть для деталей.",
    category: "brushes",
    defaultColor: "#c2d7ff",
    defaultWidth: 2.4,
    defaultOpacity: 0.8,
    strokeStyle: "solid",
    smoothing: 0.58,
  },
  {
    id: "thick-brush",
    label: "Толстая кисть",
    description: "Широкие уверенные штрихи в духе постеров и speed art.",
    category: "brushes",
    defaultColor: "#ff9d8c",
    defaultWidth: 10,
    defaultOpacity: 0.72,
    strokeStyle: "solid",
    smoothing: 0.68,
  },
  {
    id: "felt-tip",
    label: "Фломастер",
    description: "Яркая чуть шероховатая линия для заметных акцентов.",
    category: "markers",
    defaultColor: "#9dc7ff",
    defaultWidth: 4.8,
    defaultOpacity: 0.82,
    strokeStyle: "marker",
    smoothing: 0.4,
  },
  {
    id: "charcoal",
    label: "Уголь",
    description: "Матовый фактурный штрих для грубых зарисовок.",
    category: "special",
    defaultColor: "#c9cbc7",
    defaultWidth: 7,
    defaultOpacity: 0.52,
    strokeStyle: "grain",
    smoothing: 0.18,
  },
  {
    id: "eraser",
    label: "Ластик",
    description: "Стирает линии на холсте, не трогая текст и вложения.",
    category: "special",
    defaultColor: "#ffffff",
    defaultWidth: 16,
    defaultOpacity: 1,
    strokeStyle: "eraser",
    smoothing: 0.3,
  },
];

export const defaultToolPresetId: ToolPresetId = "ballpoint";

export function getToolPreset(toolId: ToolPresetId) {
  return toolPresets.find((preset) => preset.id === toolId) ?? toolPresets[0]!;
}

